error handling helm upgrade

diff --git a/Tasks/helm-install.yaml b/Tasks/helm-install.yaml
--- a/Tasks/helm-install.yaml
+++ b/Tasks/helm-install.yaml
@@ -18,12 +18,23 @@ spec:
   workspaces:
     - name: source
       mountpath: /source
+  results:
+    - name: state
+      description: state
+    - name: description
+      description: description
   steps:
   - name: helm-install
     image: alpine/helm:3.2.1
     script: |
       cd /source
-      helm upgrade --install --force $(params.repo-name) $(params.src)
+      helm upgrade --install --force $(params.repo-name) $(params.src) > /tekton/results/description
+      if [ "$?" = 0 ]; then
+        printf "success" > /tekton/results/state
+      else
+        printf "failure" > /tekton/results/state
+      fi
+      exit 0
   - name: update-github-finished
     env:
       - name: GITHUBTOKEN
@@ -33,5 +44,7 @@ spec:
             key: token
     image: curlimages/curl:latest
     script: |
-      curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"success\", \"target_url\": \"$(params.target_url)\", \"description\": \"deploy yaml finished\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
+      state=$(cat /tekton/results/state)
+      description=$(cat /tekton/results/description)
+      curl -X POST -H 'Content-Type: application/json' --data "{\"state\":\"${state}\", \"target_url\": \"$(params.target_url)\", \"description\": \"${description}\", \"context\": \"$(params.github-context)\"}" https://$GITHUBTOKEN:x-oauth-basic@api.github.com/repos/$(params.repo-full-name)/statuses/$(params.revision)
       exit 0
